---
index: true
meta: 
  title: "BronSec Inc"
  description: "Strategic Security Solutions"
  keywords: "security, information security consulting, infosec, hacking, penetration testing, security review, security compliance, HIPAA, ISO27001, SOC2, risk assessment, application security"
  image: "/img/logo1.png"
sections: 
  - "guide"
