---
-
  name: Consulting and strategic security
  services:
    - Secure development lifecycle
    - Building security into your business process
    - Security policy development
-
  name: Compliance
  services:
    - Specific expertise in assisting cloud based businesses with compliance
    - Building controls for odern engineering practices to achieve compliance objectives 
    - Successful certifications including ISO27001, SOC2 and HIPAA
    - Risk assessments
-
  name: Security reviews and penetration testing
  services:
    - Web applications
    - Mobile applications
    - API and code review
    - Network testing
    - Operational security

